name       : xdg-user-dirs
version    : '0.17'
release    : 7
source     :
    - https://user-dirs.freedesktop.org/releases/xdg-user-dirs-0.17.tar.gz : 2a07052823788e8614925c5a19ef5b968d8db734fdee656699ea4f97d132418c
homepage   : http://www.freedesktop.org/wiki/Software/xdg-user-dirs/
component  : desktop.core
license    :
    - GPL-2.0-only
summary    : Tool to manage well known user directories
description: |
    xdg-user-dirs is a tool to help manage "well known" user directories like the desktop folder and the music folder. It also handles localization (i.e. translation) of the filenames.
setup      : |
    %patch -p1 < $pkgfiles/0001-Convert-to-a-stateless-configuration.patch
    %reconfigure --disable-documentation
build      : |
    %make
install    : |
    %make_install
    install -m 00644 -D $pkgfiles/xdg-user-dirs.service $installdir/usr/lib/systemd/user/xdg-user-dirs.service
    install -D -d -m 00755 $installdir/usr/lib/systemd/user/default.target.wants
    ln -sv ../xdg-user-dirs.service $installdir/usr/lib/systemd/user/default.target.wants/xdg-user-dirs.service
