name        : xdg-user-dirs
version     : 0.15
release     : 4
source      :
    - http://user-dirs.freedesktop.org/releases/xdg-user-dirs-0.15.tar.gz : 20b4a751f41d0554bce3e0ce5e8d934be98cc62d48f0b90a894c3e1916552786
homepage    : http://www.freedesktop.org/wiki/Software/xdg-user-dirs/
license     :
    - GPL-2.0
summary     : Tool to manage well known user directories
description : |
    xdg-user-dirs is a tool to help manage "well known" user directories like the desktop folder and the music folder. It also handles localization (i.e. translation) of the filenames.
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-man-pages-due-to-build-failure.patch
    %patch -p1 < $pkgfiles/0001-Convert-to-a-stateless-configuration.patch
    autoreconf -vfi
    %configure --disable-documentation
build      : |
    %make
install    : |
    %make_install
    install -m 00644 -D $pkgfiles/xdg-user-dirs.desktop $installdir/usr/share/xdg/autostart/xdg-user-dirs.desktop
